# Fichier contenant les constantes pour les differents tests

# Semantic Map Questions
TOTAL_RANDOM_CHOICES = 5
TOTAL_RANDOM_CHOICES_N_TOPIC_MAX = 5
TOTAL_RANDOM_CHOICES_N_WORDS_MAX = 5
QUESTION_3_TOPIC_ID = '25'
QUESTION_4_TOPIC_1 = '20'
QUESTION_4_TOPIC_2 = '21'

# Video listening test
VIDEO_LISTENING_TOPIC_ID = 't_2'
VIDEO_LISTENING_TOP_N_VIDEOS = 5
VIDEO_LISTENING_N_INTRUDER = 3


# Sys-Rec GLOBAL
TOP_N_VIDEOS_COLD_START = 5
TOP_N_VIDEOS = 3 #5
N_TOPIC_BUILDING_USER_INTEREST_AREA = 3
MAX_VIDEOS_CAN_BE_WATCH = 20

# Calcul des recommendations et centre d'interet
NEW_REC_OPTION = 5
CALCULATE_CI_OPTION = 2
RECOMMENDATION_THRESHOLD_MIN = 0.4



